version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "chore(deps)"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
    groups:
      go-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "chore(deps)"
    groups:
      npm-dependencies:
        patterns: ["*"]
